[package]
name = "sfwallpaper"
version = "0.1.0"
authors = ["Zach Reizner <zach297@gmail.com>"]

[dependencies]
base64 = "0.3"
docopt = "0.7"
docopt_macros = "0.7"
hyper = "0.9"
rand = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
serde_json = "0.9"
