[package]
name = "sfwallpaper"
version = "0.1.0"
authors = ["Zach Reizner <zach297@gmail.com>"]

[dependencies]
hyper = "0.9"
serde_json = "0.9"
base64 = "~0.3.0"
docopt = "0.7"
docopt_macros = "0.7"
rustc-serialize = "0.3"
rand = "0.3"
